<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>LumiSoft.Net.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Security" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="TimerEx.cs">
      <SubType>Component</SubType>
    </Compile>
    <None Include="POP3\POP3_ExtendedCapabilities.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="license.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.2" />
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="POP3\Server\POP3_Session.cs" />
    <Compile Remove="POP3\Server\POP3_ServerMessage.cs" />
    <Compile Remove="POP3\Server\POP3_Server.cs" />
    <Compile Remove="POP3\Server\POP3_e_Started.cs" />
    <Compile Remove="POP3\Server\POP3_e_GetTopOfMessage.cs" />
    <Compile Remove="POP3\Server\POP3_e_GetMessageStream.cs" />
    <Compile Remove="POP3\Server\POP3_e_GetMessagesInfo.cs" />
    <Compile Remove="POP3\Server\POP3_e_DeleteMessage.cs" />
    <Compile Remove="POP3\Server\POP3_e_Authenticate.cs" />
    <Compile Remove="POP3\Server\AuthUser_EventArgs.cs" />
    <Compile Remove="POP3\POP3_ExtendedCapabilities.cs" />
  </ItemGroup>
</Project>