<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
    <OutputType>Library</OutputType>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
    <RestorePackages>true</RestorePackages>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="html_email_with_bad_header.txt" />
    <EmbeddedResource Include="html_email_with_image_attachment.txt" />
    <EmbeddedResource Include="html_email_with_body_image.txt" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BugNET.BLL\BugNET.BLL.csproj" />
    <ProjectReference Include="..\BugNET.Common\BugNET.Common.csproj" />
    <ProjectReference Include="..\BugNET.DAL\BugNET.DAL.csproj" />
    <ProjectReference Include="..\BugNET.Entities\BugNET.Entities.csproj" />
    <ProjectReference Include="..\BugNET.MailboxReader\BugNET.MailboxReader.csproj" />
    <ProjectReference Include="..\Library\Providers\DataProviders\SqlDataProvider\Provider.SqlDataProvider.csproj" />
    <ProjectReference Include="..\Library\Providers\MembershipProviders\Provider.MembershipProviders.csproj" />
    <ProjectReference Include="..\LumiSoft.Net\LumiSoft.Net.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="NewMailboxIssue.xslt" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="html_email_with_message_attachment.txt" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="rtf_email_with_image_attachment.txt" />
    <EmbeddedResource Include="rtf_email_with_message_attachment.txt" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.5" />
    <PackageReference Include="NUnit" Version="3.0.1" />
  </ItemGroup>
</Project>